// Test definitions. Do NOT edit this file!

#include <tuple>

#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch_amalgamated.hpp"

#include "../Sobre.hpp"
#include "../Paquete.hpp"

// =====================
// tests for exercise 1
// ---------------------

TEST_CASE("Ex1", "[Costo del sobre sin cargo adicional]")
{
    Persona rem("Maria Vargas", "Colima", "28040");
    Persona des("Juan Perez", "Guadalajara", "44630");
    Sobre s1(rem, des, 15, 10);
    SECTION("Verificando el cálculo del costo del sobre sin adicional")  
    {
        REQUIRE(s1.calculaCosto() == 150.50);
    }
} 

// =====================
// tests for exercise 2
// ---------------------

TEST_CASE("Ex2", "[Costo del sobre con cargo adicional]")
{
    Persona rem("Maria Vargas", "Colima", "28040");
    Persona des("Juan Perez", "Guadalajara", "44630");
    Sobre s1(rem, des, 35, 20);
    SECTION("Verificando el cálculo del costo del sobre con adicional")  
    {
        REQUIRE(s1.calculaCosto() == 230.40);
    }
} 

TEST_CASE("Ex3", "[Costo del paquete]")
{
    Persona rem("Maria Vargas", "Colima", "28040");
    Persona des("Juan Perez", "Guadalajara", "44630");
    Paquete p1(rem, des, 5, 10, 15, 20);
    SECTION("Verificando el cálculo del costo del paquete")  
    {
        REQUIRE(p1.calculaCosto() == 267.75);
    }
} 

TEST_CASE("Ex4", "[Imprime del sobre]")
{
    Persona rem("Maria Vargas", "Colima", "28040");
    Persona des("Juan Perez", "Guadalajara", "44630");
    Sobre s1(rem, des, 15, 10);
    SECTION("Imprime del sobre")  
    {
        s1.imprime();
        REQUIRE(true);
    }
}

TEST_CASE("Ex5", "[Imprime del paquete]")
{
    Persona rem("Maria Vargas", "Colima", "28040");
    Persona des("Juan Perez", "Guadalajara", "44630");
    Paquete p1(rem, des, 5, 10, 15, 20);
    SECTION("Verificando la impresión del paquete")  
    {
        p1.imprime();
        REQUIRE(true);
    }
} 

TEST_CASE("Ex6", "[Creación del paquete]")
{
    Persona rem("Maria Vargas", "Colima", "28040");
    Persona des("Juan Perez", "Guadalajara", "44630");
    Paquete p1(rem, des, 5, 10, 15, 20);
    SECTION("Verificando la creación del paquete")
    {
        REQUIRE(p1.getPeso() == 5);
        REQUIRE(p1.getAncho() == 10);       
        REQUIRE(p1.getLargo() == 15);
        REQUIRE(p1.getProfundidad() == 20);
    }
} 

TEST_CASE("Ex7", "[Creación del sobre]")
{
    Persona rem("Maria Vargas", "Colima", "28040");
    Persona des("Juan Perez", "Guadalajara", "44630");
    Sobre s1(rem, des, 5, 10);
    SECTION("Verificando la creación del sobre")
    {
        REQUIRE(s1.getAncho() == 5);
        REQUIRE(s1.getLargo() == 10);       
    }   
} 

